const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  getServerInfo: () => ipcRenderer.invoke('get-server-info'),
  startServer: (serverPath) => ipcRenderer.send('start-server', serverPath),
  stopServer: () => ipcRenderer.send('stop-server'),
  kickClient: (socketId) => ipcRenderer.send('kick-client', socketId),
  callClient: (socketId) => ipcRenderer.send('call-client', socketId),
  restartAll: () => ipcRenderer.send('restart-all'),
  restartClient: (socketId) => ipcRenderer.send('restart-client', socketId),
  setClientDevice: (socketId, kind, deviceId) => ipcRenderer.send('set-client-device', { socketId, kind, deviceId }),
  setClientMediaState: (socketId, kind, enabled) => ipcRenderer.send('set-client-media-state', { socketId, kind, enabled }),
  refreshClientDevices: (socketId) => ipcRenderer.send('refresh-client-devices', socketId),
  setClientChannel: (socketId, channelId) => ipcRenderer.send('set-client-channel', { socketId, channelId }),
  forceUpdate: (appType) => ipcRenderer.send('force-update', { appType }),
  getSystemSettings: () => ipcRenderer.invoke('get-system-settings'),
  selectUpdateFolder: () => ipcRenderer.invoke('select-update-folder'),
  scanUpdateFolder: () => ipcRenderer.invoke('scan-update-folder'),
  clearUpdateFolder: () => ipcRenderer.invoke('clear-update-folder'),
  onUpdateScanResult: (callback) => ipcRenderer.on('update-scan-result', (event, result) => callback(result)),
  saveSystemSettings: (settings) => ipcRenderer.invoke('save-system-settings', settings),
  listRegisteredClients: () => ipcRenderer.invoke('list-registered-clients'),
  saveRegisteredClient: (client) => ipcRenderer.invoke('save-registered-client', client),
  removeRegisteredClient: (id) => ipcRenderer.invoke('remove-registered-client', id),
  probeRegisteredClient: (id) => ipcRenderer.invoke('probe-registered-client', id),
  configureRegisteredClient: (id, config) => ipcRenderer.invoke('configure-registered-client', id, config),
  restartRegisteredClient: (id) => ipcRenderer.invoke('restart-registered-client', id),
  onServerStatus: (callback) => ipcRenderer.on('server-status', (event, status) => callback(status)),
  onServerLog: (callback) => ipcRenderer.on('server-log', (event, log) => callback(log)),
  onServerStats: (callback) => ipcRenderer.on('server-stats', (event, stats) => callback(stats))
});
