'use strict';

const fs = require('fs');
const path = require('path');
const { Readable } = require('stream');

function isStrictlyWithin(root, candidate) {
  const relative = path.relative(root, candidate);
  return !!relative && relative !== '..' && !relative.startsWith(`..${path.sep}`) &&
    !path.isAbsolute(relative);
}

/**
 * Resolve, validate and open one indexed media file exactly once.
 * The caller owns the returned handle and must close it.
 */
async function openVerifiedMediaFile(configuredRoot, relativeFile) {
  const raw = String(relativeFile || '');
  if (!configuredRoot || !path.isAbsolute(configuredRoot) || !raw || raw.length > 4096 ||
      path.isAbsolute(raw)) return null;

  const root = path.resolve(configuredRoot);
  const absolute = path.resolve(root, raw);
  if (!isStrictlyWithin(root, absolute)) return null;

  let handle = null;
  try {
    const [rootReal, pathStat, real] = await Promise.all([
      fs.promises.realpath(root),
      fs.promises.lstat(absolute),
      fs.promises.realpath(absolute),
    ]);
    if (!pathStat.isFile() || pathStat.isSymbolicLink() || !isStrictlyWithin(rootReal, real)) {
      return null;
    }

    const noFollow = fs.constants.O_NOFOLLOW || 0;
    handle = await fs.promises.open(real, fs.constants.O_RDONLY | noFollow);
    const openedStat = await handle.stat();
    if (!openedStat.isFile()) {
      await handle.close().catch(() => {});
      return null;
    }

    // If an intermediate directory was replaced between realpath and open,
    // fstat will not describe the file validated by lstat. POSIX filesystems
    // expose stable dev+ino values; O_NOFOLLOW still protects the final path
    // component on platforms where those identifiers are unavailable.
    const stableIdentity = Number(pathStat.dev) !== 0 && Number(pathStat.ino) !== 0 &&
      Number(openedStat.dev) !== 0 && Number(openedStat.ino) !== 0;
    if (stableIdentity &&
        (pathStat.dev !== openedStat.dev || pathStat.ino !== openedStat.ino)) {
      await handle.close().catch(() => {});
      return null;
    }
    return { handle, stat: openedStat, filePath: real };
  } catch {
    await handle?.close().catch(() => {});
    return null;
  }
}

function mimeOf(filePath) {
  const extension = path.extname(String(filePath || '')).toLowerCase();
  if (extension === '.mp4') return 'video/mp4';
  if (extension === '.webm') return 'video/webm';
  return 'video/x-matroska';
}

// Recording identifiers generated by the server are URL-safe already.  In
// particular, do not accept percent-encoded separators here: forwarding an
// encoded slash to an HTTP router can make the custom-protocol allow-list and
// the server's decoded route disagree about the requested resource.
const SERVER_MEDIA_PATH_RE = /^\/recordings\/(media|live)\/([A-Za-z0-9._~!$&'()*+,;=:@-]{1,256})$/;

function validateServerMediaPath(rawPath, expectedKind = null) {
  const value = String(rawPath || '');
  const match = SERVER_MEDIA_PATH_RE.exec(value);
  if (!match || (expectedKind && match[1] !== expectedKind)) return null;
  return value;
}

function parseByteRange(rangeHeader, totalBytes) {
  if (rangeHeader == null || rangeHeader === '') return null;
  const value = String(rangeHeader);
  if (value.length > 128 || !Number.isSafeInteger(totalBytes) || totalBytes <= 0) return false;
  const match = /^bytes=(\d*)-(\d*)$/.exec(value);
  if (!match || (!match[1] && !match[2])) return false;

  let start;
  let end;
  if (!match[1]) {
    const suffixLength = Number(match[2]);
    if (!Number.isSafeInteger(suffixLength) || suffixLength <= 0) return false;
    start = Math.max(0, totalBytes - suffixLength);
    end = totalBytes - 1;
  } else {
    start = Number(match[1]);
    end = match[2] ? Number(match[2]) : totalBytes - 1;
    if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) ||
        start < 0 || end < start || start >= totalBytes) return false;
    end = Math.min(end, totalBytes - 1);
  }
  return { start, end };
}

/**
 * Build the deliberately small set of headers/options that may be forwarded
 * from recmedia://server to the configured recording server.
 */
function serverMediaFetchOptions(request, accessToken = '') {
  const method = String(request?.method || 'GET').toUpperCase();
  if (!['GET', 'HEAD'].includes(method)) return null;

  const headers = {};
  const token = String(accessToken || '');
  if (token) headers.Authorization = `Bearer ${token}`;
  const range = request?.headers?.get?.('Range');
  if (range) headers.Range = range;
  return { method, headers };
}

/** Build a GET/HEAD/Range Response from the already validated FileHandle. */
async function recordingFileResponse(opened, {
  rangeHeader = null,
  method = 'GET',
  signal = null,
} = {}) {
  const { handle, stat, filePath } = opened || {};
  if (!handle || !stat) return new Response('not found', { status: 404 });

  let stream = null;
  let closePromise = null;
  const closeHandle = () => {
    if (!closePromise) {
      signal?.removeEventListener?.('abort', abortTransfer);
      closePromise = handle.close().catch(() => {});
    }
    return closePromise;
  };
  const abortTransfer = () => {
    if (stream && !stream.destroyed) stream.destroy();
    void closeHandle();
  };
  signal?.addEventListener?.('abort', abortTransfer, { once: true });

  try {
    if (signal?.aborted) {
      await closeHandle();
      return new Response(null, { status: 499 });
    }

    const requestMethod = String(method || 'GET').toUpperCase();
    if (!['GET', 'HEAD'].includes(requestMethod)) {
      await closeHandle();
      return new Response(null, { status: 405, headers: { Allow: 'GET, HEAD' } });
    }

    const total = Number(stat.size);
    if (!Number.isSafeInteger(total) || total < 0) {
      await closeHandle();
      return new Response('invalid media file size', { status: 500 });
    }
    const range = parseByteRange(rangeHeader, total);
    const headers = {
      'Content-Type': mimeOf(filePath),
      'Accept-Ranges': 'bytes',
      'Cache-Control': 'private, no-store',
    };
    if (stat.mtime instanceof Date && Number.isFinite(stat.mtimeMs)) {
      headers['Last-Modified'] = stat.mtime.toUTCString();
    }
    if (range === false) {
      headers['Content-Range'] = `bytes */${total}`;
      await closeHandle();
      return new Response(null, { status: 416, headers });
    }

    const start = range ? range.start : 0;
    const end = range ? range.end : total - 1;
    const length = range ? end - start + 1 : total;
    const status = range ? 206 : 200;
    headers['Content-Length'] = String(length);
    if (range) headers['Content-Range'] = `bytes ${start}-${end}/${total}`;

    if (requestMethod === 'HEAD' || total === 0) {
      await closeHandle();
      return new Response(null, { status, headers });
    }

    stream = handle.createReadStream({ start, end, autoClose: false });
    stream.once('end', closeHandle);
    stream.once('close', closeHandle);
    stream.once('error', closeHandle);
    try {
      return new Response(Readable.toWeb(stream), { status, headers });
    } catch (err) {
      stream.destroy();
      await closeHandle();
      throw err;
    }
  } catch (err) {
    if (stream && !stream.destroyed) stream.destroy();
    await closeHandle();
    throw err;
  }
}

module.exports = {
  openVerifiedMediaFile,
  parseByteRange,
  recordingFileResponse,
  serverMediaFetchOptions,
  validateServerMediaPath,
};
